ToDoAppFromScratch/ToDoAppFromScratch/Models/Tasks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoAppFromScratch.Models
{
    public class Tasks
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
    }
}

ToDoAppFromScratch/ToDoAppFromScratch/Models/ToDoEntity.cs
namespace ToDoAppFromScratch.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class ToDoEntity : DbContext
    {
        public ToDoEntity()
            : base("name=ToDoEntity")
        {

        }

        public DbSet<Tasks> Tasks { get; set; }
        
          
    }

    public class ToDoDBCreator : DropCreateDatabaseIfModelChanges<ToDoEntity>
    {

    }
}

ToDoAppFromScratch/ToDoAppFromScratch/ViewModels/ToDo/ToDoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ToDoAppFromScratch.Models;

namespace ToDoAppFromScratch.ViewModels.ToDo
{
    public class ToDoViewModel
    {
        public int Id { get; set; }
        public string TaskName { get; set; }

        public IEnumerable<Tasks> TaskTable { get; set; }
    }
}

ToDoAppFromScratch/ToDoAppFromScratch/Controllers/DemoRepoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoAppFromScratch.Models;
using ToDoAppFromScratch.Repository;
using ToDoAppFromScratch.UnitOfWork;
using ToDoAppFromScratch.ViewModels.ToDo;

namespace ToDoAppFromScratch.Controllers
{
    public class DemoRepoController : Controller
    {
        GenericUnitOfWork unitOfWork;
        // GET: DemoRepo
        public ActionResult Index()
        {
            unitOfWork = new GenericUnitOfWork();
            ToDoViewModel toDoList = new ToDoViewModel();
            toDoList.TaskTable = unitOfWork.GetRepoInstance<Tasks>().SelectAll();
            return View(toDoList);
        }

        public ActionResult AddEditItem(Tasks task)
        {
            unitOfWork = new GenericUnitOfWork();
            GenericRepository<Tasks> tasksRepo = unitOfWork.GetRepoInstance<Tasks>();

            if (task.Id == 0)
            {
                tasksRepo.Insert(task);

            }

            else
            {
                Tasks taskToUpdate = tasksRepo.SelectByID(task.Id);
                taskToUpdate.TaskName = task.TaskName;
            }
            unitOfWork.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult RemoveItem(Tasks task)
        {
            unitOfWork = new GenericUnitOfWork();
            GenericRepository<Tasks> tasksRepo = unitOfWork.GetRepoInstance<Tasks>();
            tasksRepo.Delete(task.Id);
            unitOfWork.SaveChanges();

            return RedirectToAction("Index");

        }

        public ActionResult EditItem(int Id)
        {
            unitOfWork = new GenericUnitOfWork();
            GenericRepository<Tasks> tasksRepo = unitOfWork.GetRepoInstance<Tasks>();
            Tasks taskToEdit = tasksRepo.SelectByID(Id);

            ToDoViewModel mod = new ToDoViewModel();
            mod.Id = taskToEdit.Id;
            mod.TaskName = taskToEdit.TaskName;
            mod.TaskTable = tasksRepo.SelectAll();
            return View("Index", mod);

        }
    }
}

ToDoAppFromScratch/ToDoAppFromScratch/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ToDoAppFromScratch.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ToDoAppFromScratch/ToDoAppFromScratch/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoAppFromScratch.Models;
using ToDoAppFromScratch.ViewModels.ToDo;

namespace ToDoAppFromScratch.Controllers
{
    public class ToDoController : Controller
    {
        ToDoEntity db = new ToDoEntity();
        public ActionResult Index()
        {
            ToDoViewModel todolist = new ToDoViewModel();
            todolist.TaskTable = db.Tasks.ToList();
            return View(todolist);
        }

        public ActionResult AddItem(ToDoViewModel mod)
        {
            if(mod.Id==0)
            {
                Tasks task = new Tasks();
                task.TaskName = mod.TaskName;
                db.Tasks.Add(task);
                db.SaveChanges();
            }
            
            else
            {
                Tasks EditTask = db.Tasks.Find(mod.Id);
                EditTask.TaskName = mod.TaskName;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult RemoveItem(ToDoViewModel mod)
        {
            Tasks DeleteTask = db.Tasks.Find(mod.Id);
            db.Tasks.Remove(DeleteTask);
            db.SaveChanges();
            mod.Id = 0;
            return RedirectToAction("Index");

        }

        public ActionResult EditItem(ToDoViewModel mod)
        {
            Tasks EditTask = db.Tasks.Find(mod.Id);
            mod.TaskName = EditTask.TaskName;
            mod.Id = EditTask.Id;
            //ToDoViewModel todolist = new ToDoViewModel();
            //todolist.TaskTable = db.Tasks.ToList();
            mod.TaskTable = db.Tasks.ToList();
            return View("Index", mod);

        }
    }
}

ToDoAppFromScratch/ToDoAppFromScratch/Views/DemoRepo/Index.cshtml
@model ToDoAppFromScratch.ViewModels.ToDo.ToDoViewModel
@{
    ViewBag.Title = "Index";
}
<h1>Add a Task</h1><br />
@using (Html.BeginForm("AddEditItem", "DemoRepo", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    <div class="form-inline">
        @Html.TextBoxFor(m => m.TaskName, new { @class = "form-control" })
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
    <br />

    <p style="font-size:large">To do list</p>

    foreach (var item in Model.TaskTable)
    {
        <ul class="list-group">
            <li class="form-inline">
                @Html.Label(item.TaskName,new { @class= "col-md-4" })
                <input type="button" value="Edit" class="btn btn-success" onclick="location.href='@Url.Action("EditItem","DemoRepo",new {Id = @item.Id})'" />
                <input type="button" value="Remove" class="btn btn-danger" onclick="location.href='@Url.Action("RemoveItem","DemoRepo",new { Id= @item.Id})'" />

            </li>
        </ul>
    }
}

ToDoAppFromScratch/ToDoAppFromScratch/Views/ToDo/Index.cshtml
@model ToDoAppFromScratch.ViewModels.ToDo.ToDoViewModel
@{
    ViewBag.Title = "Index";
}
<h1>Add a Task</h1><br />
@using (Html.BeginForm("AddItem", "ToDo", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    <div class="form-inline">
        @Html.TextBoxFor(m => m.TaskName, new { @class = "form-control" })
        <input type="submit" value="Add" class="btn btn-primary" />
    </div>
   <br />

     <p style="font-size:large">To do list</p>
     
     foreach (var item in Model.TaskTable)
     {
         <ul>
             <li>
                 @Html.Label(item.TaskName)
                 <input type="button" value="Edit" class="btn btn-success" onclick="location.href='@Url.Action("EditItem","ToDo",new {Id = @item.Id})'" />
                 <input type="button" value="Remove" class="btn btn-danger" onclick="location.href='@Url.Action("RemoveItem","ToDo",new { Id= @item.Id})'" />

             </li>
         </ul>
     }
}